### ISSUE TITLE
[ EVENT ] SWOT Ocean Workshop

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/how_we_work#36]
## Details from Mentor: 
**What:** SWOT oceans simulated data in the cloud Workshop
**Where:** virtual
**When:** March 16-17 (9am-12pm PT)
**Who:** 11 SWOT ST oceanography PIs, and their labs/teams
**Mentor Point of Contact:** Catalina Oaida @ScienceCat18 

## TODOs

- [x] help set up quarto book if needed - @jules32 
  - instructions: https://openscapes.github.io/quarto-website-tutorial/first-observations.html#fork-to-your-account
- [x] share 2i2c JupyterHub access form with participants - @ScienceCat18 
- [x] add participants to JupyterHub - @erinmr or @jules32 – list attached in Catalina's email
- [x] create a 2i2c event Issue - @jules32 
  - https://github.com/2i2c-org/infrastructure/issues/1076
 - [x] update/activate the 2i2c Hub button in [SWOT Quarto Book](https://podaac.github.io/2022-SWOT-Ocean-Cloud-Workshop/tutorials/00_Setup.html), if you think that’s a good idea @jules32
- [x] how to update logo in upper left (to podaac only, right now it has the cloud hackathon logos) @jules32 
- [x] I’d like to copy instructions/create tutorial on how to end 2i2c session in the SWOT quarto book (right now takes us to another Quarto book, and I don’t want to confuse people if they don’t pay attention and start navigating through that other quarto book). Any ideas how to best do this? @jules32 
   - how about linking to https://podaac.github.io/2022-SWOT-Ocean-Cloud-Workshop/tutorials/00_Setup.html#how-do-i-end-my-session? Julie can do this
