### ISSUE TITLE
[ EVENT ] ECOSTRESS

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/how_we_work#37]
## Details from Mentor: 
**What:** ECOSTRESS Workshop
**Where:** virtual
**When:** April 12-13. Office Hours on April 14. Additional 1 day event with U Tenn 2 weeks later
**Who:** 
**Mentor Point of Contact:** @amfriesz 

## TODOs

- [x] help set up quarto book if needed - @jules32 
  - instructions: https://openscapes.github.io/quarto-website-tutorial/first-observations.html#fork-to-your-account
- [ ] share 2i2c JupyterHub access form with participants - @amfriesz 
- [ ] add participants to JupyterHub - @erinmr or @jules32 
- [x] create a 2i2c event Issue - @jules32 
  - https://github.com/2i2c-org/infrastructure/issues/1076
