### ISSUE TITLE
Community Call: “GitHub Projects..." - Feb 20

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/how_we_work#50]
Community Call: “GitHub for NASA Openscapes community project management & calendaring - a work in progress” 

Purpose: share our specific use case and motivations (lightweight to welcome contributors, public to share "what's upcoming?"

**Comment by stefaniebutland** [comment]
Tues Feb 20, 10am PT / 1pm ET

**Comment by stefaniebutland** [comment]
Copying our "standard" checklist here

**Date:** Tuesday, February 20, 2024
**Time:** 10:00 - 11:00 am Pacific Time
**Location:** Zoom, (via zoom registration)

## Agenda

Example times (PT)

- 9:45 - sign into Zoom to setup/check audio etc
- 9:55 - start rotating slides and letting people in Zoom
	- one slide says we'll start at at :02 after, say hello in Chat
- 10:00 - start pump up music, slides keep rotating
- 10:02 - welcome 
- 10:05 - Celebrity interview or other format
- 10:30 - Audience Q & A
- 10:50 - closing & thank you
- 10:55 - end

Examples of previous Openscapes Community Calls: https://www.openscapes.org/tags/community-call/

## TODO

In the checklist below, DATE is placeholder for deadline, to be filled in.

- [ ] create draft Google Doc for event 
- [ ] set up eventbrite page with registration, zoom link; add zoom link to Google Invites & Doc DATE
- [ ] create page at https://openscapes.org/events
- [ ] tweet announcement, DATE
- [ ] planning meeting with speakers, Stef, Julie, 1-week prior to event, DATE
- [ ] engage potential participants / stakeholders
- [ ] tweet reminder DATE
- [ ] ask speakers about their favorite pump-up song/a song he likes that we'll play at the intro
- [ ] create intro slides
- [ ] call takes place
- [ ] update Event page - event past
- [ ] publish blog post & tweet & toot
- [ ] add post link to Eventbrite page

## Content

brief notes on ideas for content

**Comment by stefaniebutland** [comment]
**Register (free)** via [Zoom](https://zoom.us/meeting/register/tJ0pf-itqD0qHdK6MSbzMP8nGs7wNrflUqZS)

**Comment by jules32** [comment]
@BriannaLind had a great idea to invite folks like GEDI and NSIDC who have seen and are doing this too! This could be a good model to follow from this 2022 Community Call with Abby Cabunoc Mayes and Chad Sansing -- we also invited other Moz Open Leaders to give smaller shares (written up in the last big paragraph: https://openscapes.org/blog/2022-01-25-open-leadership/)

**Comment by stefaniebutland** [comment]
added to [NASA-Openscapes](https://nasa-openscapes.github.io/) home page Upcoming

![Image](https://github.com/NASA-Openscapes/how_we_work/assets/11927811/7b89323b-e52e-48bf-8b9f-737a9b03e80f)

**Comment by jules32** [comment]
thank you so much!

**Comment by stefaniebutland** [comment]
Promo Feb 2.
Tooted 
Slacks
-  Openscapes
-  CSCCE
- rOpenSci
- FTS
- RLadies organizers
- RLadies community
- SOSS Standard Office Space Kamloops
- Built in Kamloops

**Comment by jules32** [comment]
- I'll share to TOPS slack too!

**Comment by stefaniebutland** [comment]
test tagging @kdchadwick

**Comment by stefaniebutland** [comment]
New issue for blog post: Blog: comm call summary - pub Feb 28 #55

**Comment by BriannaLind** [comment]
added a few comments

**Comment by BriannaLind** [comment]
@stefaniebutland can we close this?

**Comment by stefaniebutland** [comment]
I will on ~Wed when the whole checklist is done

**Comment by jules32** [comment]
Here's one example of a GitHub Project Board that came to be following the Community Call!

https://github.com/orgs/libscie/projects/3/views/2

**Comment by stefaniebutland** [comment]
I love how every iteration gives me ideas!!
